# Generated by Django 6.0.3 on 2026-03-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0006_category_expense_category_savingsgoal_saving_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
